### ISSUE TITLE
Plugin/KiCad crashes with a Memory Access Errors

### ISSUE THREAD

**Issue by worldwidemv** [gauravmm/HierarchicalPcb#1]
The plugin/KiCad dies ~0.5 seconds after I run the plugin under Linux (KDE Neon - Ubuntu 22.04 based).

The plugin seams to run through the parts of the hierarchical sheet/sub-PCB but dies shortly after it starts with the parts of the main PCB.

Any advice how I can debug this?
Running KiCad with gdb (gdb kicad) gave this:
```
Thread 1 "kicad" received signal SIGSEGV, Segmentation fault.
0x00007fff92ad72c0 in ?? () from /usr/bin/_pcbnew.kiface
```

### KiCad Info:
Application: KiCad x86_64 on x86_64

Version: 7.0.7-7.0.7~ubuntu22.04.1, release build

Libraries:
	wxWidgets 3.2.1
	FreeType 2.11.1
	HarfBuzz 6.0.0
	FontConfig 2.13.1
	libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16

Platform: KDE neon 5.27, 64 bit, Little endian, wxGTK, KDE, x11

Build Info:
	Date: Aug 13 2023 23:14:49
	wxWidgets: 3.2.1 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.74.0
	OCC: 7.5.2
	Curl: 7.88.1
	ngspice: 38
	Compiler: GCC 11.4.0 with C++ ABI 1016

Build settings:
	KICAD_SPICE=ON

**Comment by gauravmm** [comment]
Hey, thanks for reaching out. I have no idea why this is happening, but if you can generate a minimal example PCB that has this bug I'll be happy to take a look.

Also, does this happen if run on another platform (Windows/OSX)?

**Comment by gauravmm** [comment]
Hey, I don't have a Linux machine handy to reproduce this bug, so I'm closing it for now. If you have a minimal PCB example (or any insight into where the bug is), I'll be happy to look into it.
