### ISSUE TITLE
Feature: Also support Edge Cuts and Silkscreen Drawings

### ISSUE THREAD

**Issue by hrueger** [gauravmm/HierarchicalPcb#11]
Hi @gauravmm,
when using this plugin (which saves sooo much work by the way and is awesome!) we noticed that it does not recreate Drawings on the Edge Cuts Layer as well as on the Silkscreen Layer. That would be awesome to have so that we could add some custom holes and labels. Do you think this is possible?
Thanks in advance!

**Comment by OfficialDyray** [comment]
Merry Christmas: #14 
Needs some testing, and zones are currently broken (for some reason the setPostion function call isnt working for me)

**Comment by gauravmm** [comment]
Merged, thank you!
