### ISSUE TITLE
Doesn't work with KiCad 8

### ISSUE THREAD

**Issue by JLA4444** [gauravmm/HierarchicalPcb#17]
I as going to use this great looking plugin but it doesn't load correctly on KiCad 8

**Comment by gauravmm** [comment]
Thanks for the interest! This version works pretty well: https://github.com/gauravmm/HierarchicalPcb/tree/feature-kicad8

The current state of KiCAD 8 compatibility is being tracked here: #7. Mainly, we need some minor bugs fixed and a little more testing, especially with larger projects.

**Comment by JLA4444** [comment]
I have a large project to test on so tell me when you need it tested.

By large i mean many different subschematic not many different instances of the same subschematic

**Comment by gauravmm** [comment]
Much appreciated! I'll reach out to you soon, likely by next weekend.

**Comment by gauravmm** [comment]
@JLA4444 Its ready for you to test it, if you can clone it to your plugins directory. Let me know if you need help with that.

(It will take a few days to hit the actual KiCAD repo.)
