### ISSUE TITLE
How is the list of available projects determined ?

### ISSUE THREAD

**Issue by soren-UDT** [gauravmm/HierarchicalPcb#28]
Hi,

Thanks for a great plugin.

I have a fairly large project with a couple of layers of hierarchy in it.

When I start HierchicalPCB at the top level I get a list of modules, where some of them are then identified as sub-project where HierPCB can inject the layout. But I'm getting inconsistencies in which projects can be injected and which ones can not.

The log file lists the projects that can be imported. How is this determined?
I have several directories with additional modules that I would like to import, but they are not detected. So I'm trying to determine why. Any insights ??

Plugin v0.0.1 running on KiCad 8.0.5 and Python 3.9.13 (v3.9.13:6de2ca5339, May 17 2022, 11:37:23) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin.
Imported /xxxlmq62440_SOM/lmq62440_SOM.kicad_pcb, with 23 footprints, 44 tracks, and 0 drawings.
Imported /xxx/clk_gen/clk_gen.kicad_pcb, with 8 footprints, 17 tracks, and 0 drawings.
Imported /xxx/lmq62440_5V/lmq62440_5V.kicad_pcb, with 23 footprints, 43 tracks, and 0 drawings.
Imported /xxx/lmq62440_3V3/lmq62440_3V3.kicad_pcb, with 23 footprints, 45 tracks, and 0 drawings.
Imported /xxx/DebugModule/DebugModule.kicad_pcb, with 11 footprints, 57 tracks, and 0 drawings.
Imported /xxx/Root.kicad_pcb, with 701 footprints, 1539 tracks, and 6 drawings.
Imported /xxx/SDcardModule/SDcardModule.kicad_pcb, with 7 footprints, 15 tracks, and 0 drawings.
Imported /xxx/1V8GEN/1V8GEN.kicad_pcb, with 4 footprints, 7 tracks, and 0 drawings.
Imported /xxx/DisplayModules/DisplayModules.kicad_pcb, with 69 footprints, 255 tracks, and 0 drawings.
Imported /xxx/NordicModule/NordicModule.kicad_pcb, with 76 footprints, 343 tracks, and 0 drawings.
Imported /xxx/2V8GEN/2V8GEN.kicad_pcb, with 4 footprints, 5 tracks, and 0 drawings.
Imported /xxx/ModemModule/ModemModule.kicad_pcb, with 92 footprints, 298 tracks, and 0 drawings.
Imported /xxx/BatteryModule/BatteryModule.kicad_pcb, with 33 footprints, 101 tracks, and 0 drawings.
Root (+ PCB /Root.kicad_pcb)

/S

**Comment by gauravmm** [comment]
We look through all the footprints in the opened board and see what sheet file is it defined on. [Here's the section of the code.](https://github.com/gauravmm/HierarchicalPcb/blob/master/hdata.py#L249-L288)

The most likely causes of your problems are:

1. you haven't placed at least one footprint from the project you want to reference
2. the projects are outside the directory tree of the main project. (i.e. "above" or outside the folder with the main project)
