### ISSUE TITLE
Planned upgrade for KiCAD 9.0 ?

### ISSUE THREAD

**Issue by xDuinoRails** [gauravmm/HierarchicalPcb#29]
I love this plugin and base my work extensivly on it.

Q: Is there already an expected release date of the KiCAD 9.0 version of the plug-in?

https://indico.cern.ch/event/1423279/contributions/5986284/attachments/2877837/5040325/20240614_KiCad_Roadmap_2024.pdf

**Comment by OfficialDyray** [comment]
Most replicate plugins will probably be depreciated by the [Multi-Channel tool](https://forum.kicad.info/t/multi-channel-tool/55809)

**Comment by gauravmm** [comment]
Damn, that tool looks great!
