### ISSUE TITLE
Layers without additionnal components cannot be used

### ISSUE THREAD

**Issue by xDuinoRails** [gauravmm/HierarchicalPcb#30]
IS
- PCBs of schematics containing no additionall components (but labels etc.) cannot be used
- They get a strange alpha-numeric names (see below e.g. "b23a7a80")

SHOULD
- Sheets / PCBs without components should  be usable too.

WORKAROUND
- Dummy components like a testpoint solve the problem.

Hierarchical view:
![image](https://github.com/user-attachments/assets/c6260b93-d2af-4fed-9902-cd0ef236edf9)
Page view with schematics:
![image](https://github.com/user-attachments/assets/3824d972-5377-4a17-9683-29aca2335cf0)

<3 <3 <3 the plug-in

**Comment by OfficialDyray** [comment]
Components provide an easy way to track position and rotation. Other board features like drawings don't provide absolute position and rotation, which makes things tricky. You can create a special "origin" footprint specifically for translation without any board features.
[Origin.zip](https://github.com/user-attachments/files/18220427/Origin.zip)

**Comment by chatelao** [comment]
Thanks a lot for the feedback and the amazing product.
