### ISSUE TITLE
Vias not replicated in KiCad 7.0.10

### ISSUE THREAD

**Issue by OmegaRogue** [gauravmm/HierarchicalPcb#8]
![image](https://github.com/gauravmm/HierarchicalPcb/assets/24958536/4192f53f-b8e6-49af-94d9-b4dba14cd9d2)
When using hierarchical PCBs with Vias in them, they turn into small circles of trace when replicated in a parent PCB

**Comment by gauravmm** [comment]
Hey, this version is a little old, and we're working on KiCAD 8 improvements right now, so we can't spare the time to look into this. Sorry!
