### ISSUE TITLE
🐛 replication fails on some PCBs (KiCad 8.0.0)

### ISSUE THREAD

**Issue by lukas-runge** [gauravmm/HierarchicalPcb#9]
After making the plugin work with KiCad 8 by using the `feature-kicad8` branch and implementing [this workaround](https://github.com/gauravmm/HierarchicalPcb/issues/2#issuecomment-1766131050) to fix replication on the first layout I discovered a new bug. I have one component that just does not replicate.
Here is a minimal example to reproduce the issue: [non-working-component-demo.zip](https://github.com/gauravmm/HierarchicalPcb/files/14605070/non-working-component-demo.zip)
Maybe you can have a look into it @gauravmm.

Huge thanks in advance! 🙏

Kind regards
Lukas

**Comment by lukas-runge** [comment]
@gauravmm this issue was an oopsie on my side. I had not updated my components pcb from the schematic with relinking via designators enabled. Thus I had a uuid mismatch between schematic and pcb parts. 🙈

Closing the issue as it never was related to the plugin in the first place. 😇

**Comment by gauravmm** [comment]
No problem, thanks for following up!
